---

port: 4100
host: localhost
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "beRi"
keywords:    "beri, R, programming, hackseq18"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/datasnakes/beri"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:
site_image:  "img/beri.jpg"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#2E33E1'
  green:     '#7AE12D'
  purple:    '#c869bf'
  orange:    '#E16E2D'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

