---

port: 4100
host: localhost
safe: false


# site serving configuration
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


# content configuration
title:       "beRi"
keywords:    "beri, R, programming, hackseq18"
description: "beRi is a package management system for the R programming language"
source_link: "https://github.com/datasnakes/beri"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:
site_image: "img/beri.jpg"
og_image: "img/beri.jpg"


# template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#2E33E1'
  green:     '#7AE12D'
  purple:    '#c869bf'
  orange:    '#E16E2D'
  turquoise: '#0fbfcf'
  yellow: '#E1DC2E'

# Kramdown configuration
kramdown:
  auto_ids:  false

